# .github/workflows/build.yml

name: Build Cork App

on:
  workflow_dispatch:

jobs:
  build-macos:
    name: Build Cork for macOS
    runs-on: macos-14 

    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      # --- ADD THIS NEW STEP ---
      - name: List Available Xcode Versions
        run: ls -l /Applications

      # --- YOUR EXISTING STEP (to be corrected after running the step above) ---
      - name: 2. Select Xcode 16
        run: |
          # This command will fail, but the step above will show you the correct path
          sudo xcode-select -s /Applications/Xcode_16.0.app 
          xcodebuild -version

      # ... rest of your workflow
