name: Build Cork App (Alternative)
on:
  workflow_dispatch:
jobs:
  build-macos:
    name: Build Cork for macOS (Xcode 15)
    runs-on: macos-13  # Use macOS 13 which has Xcode 15
    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4
        
      - name: 2. Select Xcode 15
        run: |
          # Use Xcode 15 which should support the template format better
          sudo xcode-select -s /Applications/Xcode_15.2.app
          xcodebuild -version
          
      - name: 3. Install and set up Mise
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          eval "$($HOME/.local/bin/mise activate bash)"
      
      - name: 4. Install Tuist via Mise
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          mise install tuist
          
      - name: 5. Generate Xcode Project
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          mise trust
          mise exec tuist@4.25.0 -- tuist install
          mise exec tuist@4.25.0 -- tuist generate --no-binary-cache
          
      - name: 6. Create Export Options Plist
        run: |
          cat > ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>copy</string>
              <key>destination</key>
              <string>export</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>signingCertificate</key>
              <string>Sign to Run Locally</string>
          </dict>
          </plist>
          EOF
          
      - name: 7. Clean build folder
        run: |
          rm -rf ./build
          mkdir -p ./build
          
      - name: 8. Archive the App
        run: |
          xcodebuild archive -skipPackagePluginValidation \
            -workspace Cork.xcworkspace \
            -scheme "Self-Compiled" \
            -sdk macosx \
            -configuration Release \
            -archivePath ./build/Cork.xcarchive \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY="" \
            | tee build.log
            
      - name: 9. Export the App
        run: |
          xcodebuild -exportArchive \
            -archivePath ./build/Cork.xcarchive \
            -exportPath ./build \
            -exportOptionsPlist ExportOptions.plist
            
      - name: 10. Upload App as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Cork-App-Xcode15
          path: ./build/Cork.app
